version: "3.7"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: waltcher-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - waltcher
  php:
    build:
      args:
        user: waltcheruser
        uid: 1000
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    image: waltcherimage
    container_name: waltcher-php
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/var/www
    networks:
      - waltcher
  db:
    image: mysql:5.7
    container_name: waltcher-mysql
    restart: unless-stopped
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - waltcher-mysqldata:/var/lib/mysql
    networks:
      - waltcher
networks:
  waltcher:
    driver: bridge
volumes:
  waltcher-mysqldata:
